services:
  minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
