# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'kafka'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['kakfa1:8080','kakfa2:8080', 'kakfa3:8080','kafka4:8080']

  - job_name: 'minio-job'
    bearer_token: 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYWRtaW4iLCJleHAiOjQ4NzkyMTI2NTN9.E0IfGkHd8SXVt3KmbDrAb6uRoFILmS2chFBEJupsE7fuIY9KVJYcYBXpYpexarjrLzBXHXIA5xIbGafErw7VdA'
    metrics_path: '/minio/v2/metrics/cluster'
    scheme: 'http'
    static_configs:
    - targets: ['minio:9000']

  - job_name: 'minio-job-bucket'
    bearer_token: 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYWRtaW4iLCJleHAiOjQ4NzkyMTI2NTN9.E0IfGkHd8SXVt3KmbDrAb6uRoFILmS2chFBEJupsE7fuIY9KVJYcYBXpYpexarjrLzBXHXIA5xIbGafErw7VdA'
    metrics_path: '/minio/v2/metrics/bucket'
    scheme: 'http'
    static_configs:
    - targets: ['minio:9000']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['kakfa1:9100', 'kakfa2:9100', 'kakfa3:9100','kakfa4:9100']

  - job_name: 'kafka-exporter'
    static_configs:
    - targets: ['kakfa1:9308']
