{
 "title": "Kafka Cluster Dashboard",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "topics", "label": "Topic", "query": { "query": "label_values(topic)" } }
  ]
 },
 "panels": [
  { "title": "Consumer and Producer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Fetch Requests",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalfetchrequests_total{topic=~\"[[topics]]\", topic != \"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Producer Requests",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalproducerequests_total{topic=~\"[[topics]]\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Group Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=~\"[[topics]]\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka Broker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Partitions under replicated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_cluster_partition_underreplicated{instance=\"server1:8080\", topic=~\"$topics\"})",
     "legendFormat": "Server 1"
    },
    {
     "expr": "sum by(instance) (kafka_cluster_partition_underreplicated{instance=\"server2:8080\", topic=~\"$topics\"})",
     "legendFormat": "Server 2"
    },
    {
     "expr": "sum by(instance) (kafka_cluster_partition_underreplicated{instance=\"server3:8080\", topic=~\"$topics\"})",
     "legendFormat": "Server 3"
    }
   ]
  },
  {
   "title": "Active Brokers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activebrokercount{instance=\"server1:8080\"}",
     "legendFormat": "Server 1"
    },
    {
     "expr": "kafka_controller_kafkacontroller_activebrokercount{instance=\"server2:8080\"}",
     "legendFormat": "Server 2"
    },
    {
     "expr": "kafka_controller_kafkacontroller_activebrokercount{instance=\"server3:8080\"}",
     "legendFormat": "Server 3"
    }
   ]
  },
  {
   "title": "Broker Message Bytes In & Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_server_brokertopicmetrics_bytesin_total[$__rate_interval]))",
     "legendFormat": "{{instance}} In"
    },
    {
     "expr": "sum by(instance) (rate(kafka_server_brokertopicmetrics_bytesout_total[$__rate_interval]))",
     "legendFormat": "{{instance}} Out"
    }
   ]
  },
  {
   "title": "Max Lag in Messages btw Follower and Leader Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicafetchermanager_maxlag{job=\"kafka\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leader Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{job=\"kafka\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Messages in Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_brokertopicmetrics_messagesin_total{instance=\"server1:8080\"})",
     "legendFormat": "Server 1"
    },
    {
     "expr": "sum by(instance) (kafka_server_brokertopicmetrics_messagesin_total{instance=\"server2:8080\"})",
     "legendFormat": "Server 2"
    },
    {
     "expr": "sum by(instance) (kafka_server_brokertopicmetrics_messagesin_total{instance=\"server3:8080\"})",
     "legendFormat": "Server 3"
    }
   ]
  },
  {
   "title": "Offline Partition Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount{job=\"kafka\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}